INSERT INTO _USER(USER_ID,NAME,ADDRESS) VALUES(1, 'RAJ','Address 1');
INSERT INTO _USER(USER_ID,NAME,ADDRESS) VALUES(2, 'VIRU','Address 2');
INSERT INTO _USER(USER_ID,NAME,ADDRESS) VALUES(3, 'PRANAV','Address 3');
INSERT INTO _USER(USER_ID,NAME,ADDRESS) VALUES(4, 'JAY','Address 4');